# Generated by Django 5.2.3 on 2025-07-02 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pyment_on_get',
            new_name='payment_on_get',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='usrer',
            new_name='user',
        ),
    ]
