# Generated by Django 5.2.3 on 2025-07-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_pyment_on_get_order_payment_on_get_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='prodict',
            new_name='product',
        ),
    ]
